---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Update repositories cache and install "grafana-agent" package
  apt:
    name: grafana-agent
    update_cache: yes

- name: Create "grafana-agent" configuration file
  template:
    src: "{{ config_template | default('grafana-agent.yml.j2', true) }}"
    dest: "/etc/grafana-agent.yaml"
  notify: restart grafana-agent

- name: Create "grafana-agent" default file
  template:
    src: "{{ default_template | default('grafana-agent.j2', true) }}"
    dest: "/etc/default/grafana-agent"
  notify: restart grafana-agent

