---
- apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Update repositories cache and install "grafana-agent" package
  apt:
    name: grafana-agent
    update_cache: yes

- name: Create "grafana-agent" configuration file
  template:
    src: "grafana-agent.yml.j2"
    dest: "/etc/grafana-agent/grafana-agent.yml"
